export const ENDPOINTS_MEIRI_TODOS = "MEIRI_TODOS";
export const ENDPOINTS_MEIRI_CURRENT_DATE = "MEIRI_CURRENT_DATE";
export const ENDPOINTS_MEIRI_LOGS = "MEIRI_LOGS";
export const ENDPOINTS_SCHWARZPOLL_QUESTIONS = "SCHWARZPOLL_QUESTIONS";
export const ENDPOINTS_SCHWARZPOLL_VOTES = "SCHWARZPOLL_VOTES";
